#!/usr/bin/env ruby
$: << File.expand_path("../../lib", __FILE__)
require 'simple_sheets'

File.open("streamed.xls", "w") do |fh|
  SimpleSheets::Workbook.new(fh) do |wb|

    10.times do |i|
      puts "Table #{i+1}"
      wb.add_worksheet do |ws|

        ws.add_table do |t|
          t.add_row do |r|
            r.add_cell do |c|
              c.add_data("Hallo #{i+1}")
            end
          end

          10.times do |row|
            t.add_row do |r|
              6.times do |col|
                r.add_cell do |c|
                  c.add_data("Cell #{row+1}/#{col+1}")
                end
              end
            end
          end

        end

      end
    end
  end
end
